assignments/urls.py
from django.conf.urls import url
from assignments import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'assignments'
urlpatterns = [
    url(r'^create/$', views.CreateAssignment.as_view(), name="create"),
    url(r'^detail/(?P<pk>[-\w]+)/$', views.AssignmentDetail.as_view(), name='detail'),
    url(r'^update/(?P<pk>[-\w]+)/$', views.UpdateAssignment.as_view(), name='update'),
    url(r'^delete/(?P<pk>[-\w]+)/$', views.DeleteAssignment.as_view(), name="delete"),
    url(r'^submit/$', views.SubmitAssignmentView.as_view(), name="submit"),
    url(r'^submission/detail/(?P<pk>[-\w]+)/$', views.SubmitAssignmentDetail.as_view(), name="submit_detail"),
    url(r'^submission/delete/(?P<pk>[-\w]+)/$', views.delete_view, name="submit_delete"),
    url(r'^grade/(?P<pk>[-\w]+)/$', views.grade_assignment, name='grade')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_lms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from assignments import views
from django_lms import views as project_views
from graphene_django.views import GraphQLView
from graphene_file_upload.django import FileUploadGraphQLView

urlpatterns = [
    url(r'^$', project_views.index, name="home"),
    path('admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^assignments/', include('assignments.urls', namespace='assignments')),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^user_profile/(?P<pk>[-\w]+)/$',
        project_views.UserProfile.as_view(), name="profile"),
    url('graphql/', FileUploadGraphQLView.as_view(graphiql=True))
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'signup/$', views.SignUp.as_view(), name='signup')
]

assignments/models.py
from django.db import models
from users.models import User
from courses.models import Course
from django.urls import reverse
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from django.conf import settings

# Create your models here.
class Assignment(models.Model):
    assignment_name = models.CharField(max_length=200, blank=False)
    assignment_description = models.TextField(blank=False)
    start_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.assignment_name

    def get_absolute_url(self):
        return reverse('assignments:detail', kwargs={'pk': self.pk})

class SubmitAssignment(models.Model):
    author = models.ForeignKey(User, related_name='assignment', on_delete=models.CASCADE)
    topic = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=False)
    assignment_file = models.FileField(blank=False, upload_to='assignments')
    submitted_date = models.DateTimeField(default=timezone.now)
    assignment_ques = models.ForeignKey(Assignment, related_name="question", on_delete=models.CASCADE, null=True)
    graded = models.BooleanField(default=False)
    grade = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ]
    )

    def __str__(self):
        return self.topic

    def grade_assignment(self, grade):
        self.grade = grade
        self.graded = True
        self.save()

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.assignment_file.name))
        super().delete(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('assignments:submit_detail', kwargs={'pk': self.pk})

assignments/forms.py
from django.forms import ModelForm, DateInput, TimeInput, Form, DateTimeInput
from django import forms
from django.shortcuts import get_object_or_404
from assignments.models import SubmitAssignment, Assignment
from django.utils import timezone
from courses.models import Course
from users.models import User

class GradeAssignmentForm(ModelForm):
    
    class Meta:
        model = SubmitAssignment
        fields = ['grade']

class CreateAssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ('assignment_name', 'assignment_description',
                  'due_date', 'course')
        labels = {
            'due_date': 'Due Date (yyyy-mm-dd HH:MM)'
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        user_object = User.objects.filter(username=user.username)
        new_user_object = get_object_or_404(user_object)
        self.fields['course'].queryset = self.fields['course'].queryset.filter(teacher=new_user_object.id)

class SubmitAssignmentForm(ModelForm):
    class Meta:
        model = SubmitAssignment
        fields = ('topic', 'description', 'assignment_file', 'assignment_ques', 'author')
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        assignment = kwargs.pop('assignment_id')
        super().__init__(*args, **kwargs)
        self.fields['assignment_ques'].queryset = self.fields['assignment_ques'].queryset.filter(pk=assignment)
        self.fields['author'].queryset = self.fields['author'].queryset.filter(username=user.username)

assignments/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.views.generic.edit import FormMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import os
from django.conf import settings

# from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404
from users.models import User
from assignments.models import Assignment, SubmitAssignment
from assignments.forms import GradeAssignmentForm, CreateAssignmentForm, SubmitAssignmentForm
from courses.models import Course

# Create your views here.    
class CreateAssignment(LoginRequiredMixin, generic.CreateView):
    form_class = CreateAssignmentForm
    template_name = 'assignments/create_assignment_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class UpdateAssignment(LoginRequiredMixin, generic.UpdateView):
    model = Assignment
    form_class = CreateAssignmentForm
    template_name = 'assignments/create_assignment_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class DeleteAssignment(LoginRequiredMixin, generic.DeleteView):
    model = Assignment
    success_url = reverse_lazy('courses:list')

class SubmitAssignmentView(LoginRequiredMixin, generic.CreateView):
    form_class = SubmitAssignmentForm
    template_name = 'assignments/submitassignment_form.html'
    select_related = ('author', 'assignment_ques')
    # success_url = reverse('assignments:submit_detail')

    def get_context_data(self, **kwargs):
        assignments = Assignment.objects.filter(pk=self.request.session.get('assignment'))
        assignment_object = get_object_or_404(assignments)
        context = super(SubmitAssignmentView, self).get_context_data(**kwargs)
        context['duedate'] = assignment_object.due_date
        context['time'] = timezone.now()
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['assignment_id'] = self.request.session.get('assignment')
        kwargs['user'] = self.request.user
        return kwargs

class SubmitAssignmentDetail(LoginRequiredMixin, generic.DetailView):
    model = SubmitAssignment
    template_name = 'assignments/submitassignment_detail.html'

    def get_context_data(self, **kwargs):
        submissions = SubmitAssignment.objects.filter(pk=self.kwargs['pk'])
        submissions_object = get_object_or_404(submissions)
        context = super(SubmitAssignmentDetail, self).get_context_data(**kwargs)
        context['submissions'] = submissions_object
        return context


class AssignmentDetail(LoginRequiredMixin, generic.DetailView):
    model = Assignment

    def get_context_data(self, **kwargs):
        course_obj = Course.objects.filter(students=self.request.user.id)
        context = super(AssignmentDetail, self).get_context_data(**kwargs)
        context['course'] = course_obj
        assignment = Assignment.objects.filter(pk=self.kwargs['pk'])
        assignment_object = get_object_or_404(assignment)
        context['duedate'] = assignment_object.due_date
        context['time'] = timezone.now()
        submitassignment = SubmitAssignment.objects.filter(assignment_ques=self.kwargs['pk'])
        context['submitted'] = submitassignment
        self.request.session['assignment'] = self.kwargs['pk']
        # print(self.request.session['assignment'])
        return context


@login_required
def delete_view(request, pk):
    obj = get_object_or_404(SubmitAssignment, pk=pk)
    context = {'submission': obj}
    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect(reverse("courses:list"))
    return render(request, "assignments/submission_confirm_delete.html", context)

@login_required
def grade_assignment(request, pk):
    submission = get_object_or_404(SubmitAssignment, pk=pk)
    if request.method=="POST":
        form=GradeAssignmentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data.get('grade')
            submission.grade_assignment(data)
            return redirect('assignments:submit_detail', pk=pk)
    else:
        form = GradeAssignmentForm()
    return render(request, 'assignments/grade_form.html', {'pk':pk, 'form':form, 'submissions':submission})

assignments/templates/assignments/assignment_base.html
{% extends 'base.html' %}


{% block title %}
    
    {% block title_name %}
        
    {% endblock title_name %}
        
{% endblock title %}
    

{% block body_content %}
    
    {% block main_content %}
    
    {% endblock main_content %}

{% endblock body_content %}
    

    

assignments/templates/assignments/assignment_confirm_delete.html
{% extends 'assignments/assignment_base.html' %}

{% block title_name %}
    LMS - Confirmation
{% endblock title_name %}
    

{% block main_content %}
    {% if user.user_type == 2 %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this assignment?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="{% url 'assignments:detail' pk=assignment.pk %}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete an assignment.</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

assignments/templates/assignments/assignment_detail.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - {{assignment.assignment_name}}
{% endblock title_name %}
    

{% block main_content %}
    <div class="container">
        <h1>{{assignment.assignment_name}}</h1>
        <h4>Course: {{assignment.course}}</h4>
        <h6>Start Date: {{assignment.start_date}}</h6>
        <h6>Due Date: {{assignment.due_date}}</h6>
        
        <p>Description: {{assignment.assignment_description}}</p>
        {% if user.user_type == 2 %}
            <a href="{% url 'assignments:update' pk=assignment.pk %}" class="btn btn-warning btn-lg">Update</a>
            <a href="{% url 'assignments:delete' pk=assignment.pk %}" class="btn btn-danger btn-lg">Delete</a>

            <div class="submissions">
            <h3>Submissions</h3>
            
            {% for submissions in submitted %}
                <a href="{% url 'assignments:submit_detail' pk=submissions.pk %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{submissions.topic}}</h5>
                    <small>{{submissions.author}}</small>
                    </div>
                    <p class="mb-1">
                    {{submissions.description}}
                    </p>
                    <small>Start Date: {{submissions.submitted_date}}</small><br>
                </a>
            {% empty %}
                <h6>No Submissions</h6>
            {% endfor %}
            </div>
                

        {% else %}            
            {% if assignment.course in course %}
                {% if duedate >= time %}
                    <a href="{% url 'assignments:submit' %}" class="btn btn-success btn-lg">Submit Assignment</a>
                {% endif %}
                <div class="submissions">
                <h3>My Submissions:</h3>
                
                {% for submissions in submitted %}
                    {% if submissions.author.id == user.id %}
                        <a href="{% url 'assignments:submit_detail' pk=submissions.pk %}" class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{submissions.topic}}</h5>
                            <small>{{submissions.author}}</small>
                            </div>
                            <p class="mb-1">
                            {{submissions.description}}
                            </p>
                            <small>Start Date: {{submissions.submitted_date}}</small><br>
                        </a>
                    {% endif %}
                {% empty %}
                    <h6>No Submissions</h6>
                {% endfor %}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock main_content %}
    

assignments/templates/assignments/create_assignment_form.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
  LMS - Create Resource
{% endblock title_name %}
  
{% block main_content %}

<div class="container">
  <h1>Assignment</h1>

  {% if user.user_type == 2 %}
    <form method="POST" action="{% url 'assignments:create' %}">
      {% csrf_token %} 
      {% bootstrap_field form.assignment_name %}
      {% bootstrap_field form.assignment_description %}
      {% bootstrap_field form.due_date %}
      {% bootstrap_field form.course %}
      {{ form.name.errors }}
      <input type="submit" value="Submit" class="btn btn-success btn-lg">
    </form>
    
    
    {% else %}
        <div class="jumbotron">
            <h2>You cannot create an assignment</h2>
        </div>
    {% endif %}

</div>
{% endblock main_content %}

assignments/templates/assignments/grade_form.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Grade
{% endblock title_name %}
    

{% block main_content %}
    
    {% if user.user_type == 2 and submissions.assignment_ques.course.teacher.id == user.id %}
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div>
                    <input type="submit" value="Grade" class="btn btn-success btn-lg">
                </div>
            </form>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You cannot grade this assignment.</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

assignments/templates/assignments/submission_confirm_delete.html
{% extends 'assignments/assignment_base.html' %}

{% block title_name %}
    LMS - Confirmation
{% endblock title_name %}
    

{% block main_content %}
    {% if user.user_type == 1 and submission.author.id == user.id %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this submission?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="{% url 'assignments:submit_detail' pk=submission.pk %}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete the submission</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

assignments/templates/assignments/submitassignment_detail.html
{% extends 'assignments/assignment_base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - {{submissions.topic}}
{% endblock title_name %}
    


{% block main_content %}
    <div class="container">
        {% if submissions.assignment_ques.course.teacher.id == user.id or submissions.author.id == user.id %}
            <h1>{{submissions.topic}}</h1>
            <h4>Submitted by: {{submissions.author}}</h4>
            <h6>Submitted On: {{submissions.submitted_date}}</h6>
            <p>Description: {{submissions.description}}</p>
            <p>Submission: {{submissions.assignment_file.name}}</p>
             
            <a href="{{submissions.assignment_file.url}}" class="btn btn-lg btn-primary" download>Download</a>
            <div class="grade">
                {% if submissions.graded == False %}
                    <p>This assignment has not been graded yet.</p>
                {% else %}
                    <p>This assignment has been graded.</p>
                    <p>Grade: {{submissions.grade}}</p>
                {% endif %}
            </div>
                
            
            
            {% if user.user_type == 1 and submissions.graded == False %}
                <div>
                    <form method="POST">
                        {% csrf_token %}
                        <a href="{% url 'assignments:submit_delete' pk=submissions.pk %}" 
                        class="btn btn-danger btn-lg">Delete</a>
                    </form>
                    
                </div>
            {% else %}
                
                {% if submissions.assignment_ques.course.teacher.id == user.id %}
                    {% if submissions.graded == False %}
                        <div>
                            <a href="{% url 'assignments:grade' pk=submissions.pk %}" 
                            class="btn btn-success btn-lg">Grade</a>
                        </div>
                    {% endif %}
                {% endif %}

            {% endif %}
                
        {% else %}
            <div class="jumbotron">
                <h2>You cannot view this assignment.</h2>
            </div>
        {% endif %}
    </div>
{% endblock main_content %}
    

assignments/templates/assignments/submitassignment_form.html
{% extends 'assignments/assignment_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Submit Assignment
{% endblock title_name %}
    
{% block main_content %}
    
    {% if user.user_type == 2 %}
        <div class="container">
            <div class="jumbotron">
                <h2>Only students are allowed to submit assignments</h2>
            </div>
        </div>
    {% else %}
            
        <div class="container">
            <h2>Submit Assignment</h2>
            <form action="{% url 'assignments:submit' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {{ form.name.errors }}
                
                {% if duedate >= time %}
                    <input type="submit" value="Submit" class="btn btn-warning btn-lg">
                {% endif %}
            </form>
            <ul>
            </ul> 
        </div>
    {% endif %}
        
{% endblock main_content %}
    