courses/urls.py
from django.conf.urls import url
from courses import views

app_name = "courses"

urlpatterns = [
    url(r'^new/$', views.CreateCourse.as_view(), name="create"),
    url(r'^detail/(?P<pk>[-\w]+)/$', views.CourseDetail.as_view(), name='detail'),
    url(r'^all/', views.ListCourse.as_view(), name="list"),
    url(r'^enroll/(?P<pk>[-\w]+)/$', views.EnrollCourse.as_view(), name='enroll'),
    url(r'^unenroll/(?P<pk>[-\w]+)/$', views.UnenrollCourse.as_view(), name='unenroll'),
]

django_lms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from assignments import views
from django_lms import views as project_views
from graphene_django.views import GraphQLView
from graphene_file_upload.django import FileUploadGraphQLView

urlpatterns = [
    url(r'^$', project_views.index, name="home"),
    path('admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^assignments/', include('assignments.urls', namespace='assignments')),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^user_profile/(?P<pk>[-\w]+)/$',
        project_views.UserProfile.as_view(), name="profile"),
    url('graphql/', FileUploadGraphQLView.as_view(graphiql=True))
]

resources/urls.py
from django.conf.urls import url
from resources import views

app_name = "resources"

urlpatterns = [
    url(r'^create/$', views.CreateResource.as_view(), name="create"),
    url(r'^delete/(?P<pk>[-\w]+)/$', views.delete_view, name='delete')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'signup/$', views.SignUp.as_view(), name='signup')
]

courses/models.py
from django.db import models
from django.urls import reverse
from users.models import User

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=200)
    course_description = models.TextField()
    teacher = models.ForeignKey(User, related_name="course", on_delete=models.CASCADE)
    students = models.ManyToManyField(User, through='Enrollment', related_name="student_course")

    def __str__(self):
        return self.course_name

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['course_name']

class Enrollment(models.Model):
    course = models.ForeignKey(Course, related_name="enrollments",on_delete=models.CASCADE)
    student = models.ForeignKey(User, related_name="user_courses", on_delete=models.CASCADE)

    def __str__(self):
        self.student.username

    class Meta:
        unique_together = ('course', 'student')

courses/views.py
from django.shortcuts import render
import datetime
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404
from users.models import User
from courses.models import Course, Enrollment
from assignments.models import Assignment
from resources.models import Resource

# Create your views here.
class CreateCourse(LoginRequiredMixin, generic.CreateView):
    fields = ('course_name', 'course_description')
    model = Course

    def get(self, request,*args, **kwargs):
        self.object = None
        context_dict = self.get_context_data()
        context_dict.update(user_type=self.request.user.user_type)
        return self.render_to_response(context_dict)
    
    def form_valid(self, form):
        form.instance.teacher = self.request.user
        return super(CreateCourse, self).form_valid(form)
    
class CourseDetail(generic.DetailView):
    model = Course

    def get_context_data(self,**kwargs):
        assignments = Assignment.objects.filter(course=self.kwargs['pk'])
        resources = Resource.objects.filter(course=self.kwargs['pk'])
        context = super(CourseDetail, self).get_context_data(**kwargs)
        context['assignments'] = assignments
        context['resources'] = resources
        return context

class ListCourse(generic.ListView):
    model = Course

class EnrollCourse(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('courses:detail', kwargs={'pk':self.kwargs.get('pk')})
    
    def get(self, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs.get('pk'))

        try:
            Enrollment.objects.create(student=self.request.user, course=course)
        except:
            messages.warning(self.request, 'You are already enrolled in the course.')
        else:
            messages.success(self.request, 'You are now enrolled in the course.')
        return super().get(self.request, *args, **kwargs)

class UnenrollCourse(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('courses:detail', kwargs={'pk':self.kwargs.get('pk')})

    def get(self, *args, **kwargs):

        try:
            enrollment = Enrollment.objects.filter(
                student=self.request.user,
                course__pk=self.kwargs.get('pk')
            ).get()
        except Enrollment.DoesNotExist:
            messages.warning(self.request, 'You are not enrolled in this course.')
        else:
            enrollment.delete()
            messages.success(self.request, 'You have unenrolled from the course.')
        return super().get(self.request, *args, **kwargs)

courses/templates/courses/course_base.html
{% extends 'base.html' %}

{% block title %}
    
    {% block title_name %}
        
    {% endblock title_name %}
        
{% endblock title %}
    
{% block body_content %}
    <div class="container">
        
        {% block main_content %}
            
        {% endblock main_content %}
            
    </div>
{% endblock body_content %}
    

courses/templates/courses/course_detail.html
{% extends 'courses/course_base.html' %} 

{% block title_name %}
  LMS - {{course.course_name}}
{% endblock title_name %}
  
{% block main_content %}
<h1>{{course.course_name}}</h1>
<h4>Teacher: {{course.teacher}}</h4>
<p>Description: {{course.course_description}}</p>

{% if user.user_type == 1 %} {%if user in course.students.all%}
<a
  href="{% url 'courses:unenroll' pk=course.pk %}"
  class="btn btn-danger btn-lg"
  >Unenroll</a
>
{% else %}
<a href="{% url 'courses:enroll' pk=course.pk %}" class="btn btn-success btn-lg"
  >Enroll</a
>
{% endif %} 
{% endif %}

{% if course.teacher.id == user.id or user in course.students.all%}
  {% if user.user_type == 2 %}
    <a
      href="{% url 'assignments:create' %}"
      class="btn btn-lg btn-fill btn-warning button-stretch"
    >
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Assignment</i>
    </a>
    <a
      href="{% url 'resources:create' %}"
      class="btn btn-lg btn-fill btn-info button-stretch"
    >
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Resource</i>
    </a>
  {% endif %}
    
  <div class="assignments">
    <h3>Assignments</h3>
    <ul class="list-group">
      {% for assignment in assignments %}
      <a href="{% url 'assignments:detail' pk=assignment.pk %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{assignment.assignment_name}}</h5>
        </div>
        <p class="mb-1">
          {{assignment.assignment_description}}
        </p>
        <small>Start Date: {{assignment.start_date}}</small><br>
        <small>Due Date: {{assignment.due_date}} {{assignment.due_time}}</small>
      </a>
      {% empty %}
      <h6>No Assignments</h6>
      {% endfor %}
    </ul>
  </div>
  <div class="resources">
    <h3>Resources</h3>
    <!-- {% include 'assignments/assignment_list.html' %} -->
    <ul class="list-group">
      {% for resource in resources %}
      <div  class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{resource.resource_name}}</h5>
        </div>
        <p class="mb-1">
          Submission: {{resource.resource_file.name}}
          <a href="{{resource.resource_file.url}}" class="btn btn-sm btn-primary" download>Download</a>
        </p>
        
        {% if user.id == course.teacher.id %}
          <small><a href="{% url 'resources:delete' pk=resource.pk %}" class="btn btn-sm btn-danger">Delete</a></small>
        {% endif %}
      </div>
      {% empty %}
        <h6>No Resources</h6>
      {% endfor %}
    </ul>
  </div>
{% endif %}
  
{% endblock main_content %}

courses/templates/courses/course_form.html
{% extends 'courses/course_base.html' %}
{% load bootstrap4 %}

{% block title_name %}
    LMS - Create Course
{% endblock title_name %}
    

{% block main_content %}
    <h1>Create new Course</h1>
    
    {% if user_type == 2 %}
        <form action="{% url 'courses:create' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Create" class="btn btn-success btn-lg">
        </form>
    {% else %}
        <div class="jumbotron">
            <h2>Oops! You need to be Teacher to access this page.</h2>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

courses/templates/courses/course_list.html
{% extends 'courses/course_base.html' %} 

{% block title_name %}
  LMS - Courses
{% endblock title_name %}
  
{% block main_content %}
<div class="container">
  <div>
    <h1>All Courses</h1>

    {% if user.user_type == 2 %}
    <a
      href="{% url 'courses:create' %}"
      class="btn btn-lg btn-fill btn-success button-stretch"
    >
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Course</i>
    </a>
    {% endif %}
  </div>
    <div class="card-deck">
      {% for course_item in object_list %}
      <div>
      <div class="card" style="width: 18rem">
        <div class="card-body">
          <h5 class="card-title">{{course_item.course_name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{course_item.teacher}}</h6>
          <p class="card-text">
            {{course_item.course_description}}
          </p>
          <a href="{% url 'courses:detail' pk=course_item.pk %}" class="btn btn-primary card-link">More Info</a>
          {% if user.user_type == 1 %}
            {%if user in course_item.students.all%}
                <a href="{% url 'courses:unenroll' pk=course_item.pk %}" class="btn btn-danger card-link">Unenroll</a>
            {% else %}
                <a href="{% url 'courses:enroll' pk=course_item.pk %}" class="btn btn-success card-link">Enroll</a>
            {% endif %}
          {% endif %}

          <p>{{course_item.students.count}}
                member{{course_item.students.count|pluralize}}</p>
          
              
        </div>
      </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock main_content %}
</div>