courses/urls.py
from django.conf.urls import url
from courses import views

app_name = "courses"

urlpatterns = [
    url(r'^new/$', views.CreateCourse.as_view(), name="create"),
    url(r'^detail/(?P<pk>[-\w]+)/$', views.CourseDetail.as_view(), name='detail'),
    url(r'^all/', views.ListCourse.as_view(), name="list"),
    url(r'^enroll/(?P<pk>[-\w]+)/$', views.EnrollCourse.as_view(), name='enroll'),
    url(r'^unenroll/(?P<pk>[-\w]+)/$', views.UnenrollCourse.as_view(), name='unenroll'),
]

django_lms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from assignments import views
from django_lms import views as project_views
from graphene_django.views import GraphQLView
from graphene_file_upload.django import FileUploadGraphQLView

urlpatterns = [
    url(r'^$', project_views.index, name="home"),
    path('admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^assignments/', include('assignments.urls', namespace='assignments')),
    url(r'^resources/', include('resources.urls', namespace="resources")),
    url(r'^user_profile/(?P<pk>[-\w]+)/$',
        project_views.UserProfile.as_view(), name="profile"),
    url('graphql/', FileUploadGraphQLView.as_view(graphiql=True))
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'signup/$', views.SignUp.as_view(), name='signup')
]

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
        {% block title %}
            
        {% endblock title %}
        
    </title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&family=Raleway&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'django_lms/css/master.css' %}" />
</head>
<body>
    <div class="sidenav">
        <div class="side-items">
        <span class="sidemenu side-element"><i class="fa fa-user-circle-o fa-5x" aria-hidden="true" id="profile"></i></span>
        
        {% if user.is_authenticated %}
            <a href="{% url 'profile' pk=user.pk %}" class="sidemenu side-element">{{user}}</a>
            <a href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
            <a href="{% url 'courses:list' %}"><i class="fa fa-list-ul" aria-hidden="true"></i>All Courses</a>
            
            {% if user.user_type == 1 %}
                <span class="sidemenu"><h5 id="side-head"><i class="fa fa-list courses-icon" aria-hidden="true"></i>Your Courses</h5></span>
                {% for course in list_courses %}
                    
                    {% if user in course.students.all %}
                        <span class="course-item"><a href="{% url 'courses:detail' pk=course.pk %}" >{{course}}</a></span>
                    {% endif %}
                        
                {% endfor %}
            {% else %}
                <a href="{% url 'courses:create' %}"><i class="fa fa-plus-circle" aria-hidden="true" style="color: #5cb85c;font-size: 20px;"></i> Create New Course</a>
                <a href="{% url 'assignments:create' %}"><i class="fa fa-plus-circle" aria-hidden="true" style="color: #f0ad4e;font-size: 20px;"></i> Create New Assignment</a>
                <a href="{% url 'assignments:create' %}"><i class="fa fa-plus-circle" aria-hidden="true" style="color: #5bc0de;font-size: 20px;"></i> Create New Resource</a>
                <span class="sidemenu"><h5 id="side-head"><i class="fa fa-list courses-icon" aria-hidden="true"></i>Your Courses</h5></span>
                {% for course in list_courses %}
                    
                    {% if user.id == course.teacher.id %}
                        <span class="course-item"><a href="{% url 'courses:detail' pk=course.pk %}" >{{course}}</a></span>
                    {% endif %}
                        
                {% endfor %}                 
            {% endif %}
            <a href="{% url 'users:logout' %}" class="sidemenu"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
        {% else %}
            <a class="sidemenu side-element">Guest</a>
            <a href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
            <a href="{% url 'users:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
            <a href="{% url 'users:signup' %}"><i class="fa fa-user-plus" aria-hidden="true"></i>Signup</a>
            <a href="{% url 'courses:list' %}"><i class="fa fa-list-ul" aria-hidden="true"></i>All Courses</a>
        {% endif %}
        </div>
            
    </div>

    
        
    <div class="content">
        {% block body_content %}
            
        {% endblock body_content %}
    </div> 

</body>
</html>

templates/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
        {% block title %}
            LMS - Home
        {% endblock title %}
        
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&family=Raleway&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'django_lms/css/master.css' %}" />
</head>
<body>
    <div class="bg-light index-image">
        <div class="container py-5">
            <div class="row align-items-center py-5">
            <div class="col-lg-6">
                <h1 class="display-4">Learning Management System</h1>
                <p class="lead text-muted mb-0">Your one-stop solution to online learning.</p>
                <p><a href="{% url 'courses:list' %}" class="btn btn-primary btn-lg index-button">View All Courses</button></a>
            </div>
            <div class="col-lg-6 d-none d-lg-block"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/illus_kftyh4.png" alt="" class="img-fluid"></div>
            </div>
        </div>
    </div>
</body>
</html>

templates/user_profile.html
{% extends 'base.html' %}


{% block title %}
    LMS - Profile
{% endblock title %}
    

{% block body_content %}
    <div class="container">
        {% if user.is_authenticated %}
            <i class="fa fa-user-circle-o fa-5x" aria-hidden="true"></i>
            <h1>Username: {{user.username}}</h1>
            <h4>First Name: {{user.first_name}}</h4>
            <h4>Last Name: {{user.last_name}}</h4>
            
            <h4>Type: 
            {% if user.user_type == 1 %}
                Student
            {% else %}
                Teacher                
            {% endif %}
            </h4>
            <h5>Email: {{user.email}}</h5>
            
            {% if user.user_type == 2 %}
                <div class="card-deck">
                {% for course in course_list %}
                    
                    {% if course.teacher.id == user.id %}
                        <div class="card" style="width: 18rem">
                            <div class="card-body">
                            <h5 class="card-title">{{course.course_name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{course.teacher}}</h6>
                            <p class="card-text">
                                {{course.course_description}}
                            </p>
                            <a href="{% url 'courses:detail' pk=course.pk %}" 
                            class="btn btn-primary card-link">More Info</a>
                            <p>{{course.students.count}}
                                    member{{course.students.count|pluralize}}</p>
                            </div>
                        </div>
                    {% endif %}
                
                {% empty %}
                    <div class="jumbotron">
                        You have not created any courses yet.
                    </div>
                {% endfor %}
                </div>
            {% elif user.user_type == 1 %}
            <div class="card-deck">
                {% for course in course_list %}
                    
                    {% if user in course.students.all %}
                        <div class="card" style="width: 18rem">
                            <div class="card-body">
                            <h5 class="card-title">{{course.course_name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{course.teacher}}</h6>
                            <p class="card-text">
                                {{course.course_description}}
                            </p>
                            <a href="{% url 'courses:detail' pk=course.pk %}" class="btn btn-primary card-link">More Info</a>
                            <a href="{% url 'courses:unenroll' pk=course.pk %}" class="btn btn-danger card-link">Unenroll</a>
                            <p>{{course.students.count}}
                                    member{{course.students.count|pluralize}}</p>
                            </div>
                        </div>
                    {% endif %}
               
                {% empty %}
                    <div class="jumbotron">
                        You have not enrolled in any courses yet.
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        {% else %}
            <div class="jumbotron">
                You cannot access this profile.
            </div>
        {% endif %}

    </div>
{% endblock body_content %}
    